require: rubocop-rails

Style/StringLiterals:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

# temporary
Metrics/LineLength:
  Max: 400

Style/FrozenStringLiteralComment:
  Enabled: false

# temporary
Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/ClassLength:
  Max: 150

AllCops:
  Exclude:
    - spec/**/*
    - db/schema.rb
    - db/migrate/*
    - bin/*