version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: installing bundler
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec spec