# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: init

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Ruby, JRuby and TruffleRuby
        # You may pin to the exact commit or the version.
        # uses: ruby/setup-ruby@6f2028eda533117e2ab7a1108e3bb40b01f481bc
        uses: ruby/setup-ruby@v1.70.0
        with:
          # Engine and version to use, see the syntax in the README. Reads from .ruby-version or .tool-versions if unset.
          ruby-version: 3.0.1 # optional, default is default
          bundler-cache: true # optional, default is false

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: install sodium
        run: sudo apt-get install libsodium
        
      # run rspec test
      - name: Run rspec test
        run: bundle exec rspec

      # run rails test
      - name: Run rails test
        run: bundle exec rake test
